### PR TITLE
Fix logo preview to 200px max.

### LINKED ISSUE #26: [BUG] Limit the size of the logo preview while adding a new team
## Description

The size of a logo or a picture that is uploaded while adding a new team to the scoreboard has no limitations as of right now. While the Upload itself is not a problem, the preview resizes the entire page if it is a high quality logo or picture. To ensure the site doesnt explode, the preview of the uploaded logo or picture should be limited in size (e.g. 200px x 200px max).

## Reproduction Steps
```
1. Go to control page
2. Go to section Add Team
3. Click on 'Browse'
4. Select a big logo or picture
5. See error
```

## Screenshots

Screenshot of Bug

### PR DESCRIPTION
**Pull request by GeneralHuber**
See issue #26 

Please verify and merge if ok

### CODE REVIEW

File: frontend/src/Pages/Control/control.tsx [hunk 1]
```diff
@@ -39,6 +39,19 @@ const useStyles = createUseStyles({
...
+    maxHeight: "200px",
+    overflow: "hidden",
+  },
+  logoPreviewImage: {
+    width: "100%",
+    height: "100%",
+    objectFit: "contain",
+    top: "0",
+    left: "0",
+    margin: "10px",
```
Comment (TomHelyer) [inline frontend/src/Pages/Control/control.tsx]: Always use % as units as to make sure you don't have more than 100%. Also most common to put margins and padding on divs instead of the img itself

File: frontend/src/Pages/Control/control.tsx [hunk 2]
```diff
@@ -39,6 +39,19 @@ const useStyles = createUseStyles({
   block: {
     flexGrow: "1",
   },
+  logoPreview: {
+    maxWidth: "200px",
+    maxHeight: "200px",
```
Comment (TomHelyer) [inline frontend/src/Pages/Control/control.tsx]: If you want a consistent size id suggest using em or rem instead of px as rem/em will take the device into account

**Comment by GeneralHuber** [comment]
See new commit

**Review by TomHelyer — APPROVED** [review]
